
var animalDict: [String: String] = [
        "Ant" : "Ant has six legs",
        "Bear" : "bear",
        "Cat" : "cat three_cats",
        "Dog" : "dog",
        "Duck" : "duck five_duck",
        "Elephant" : "elephant four_elephant",
        "Eagle" : "eagle",
        "Frog" : "frog frog3",
        "Goat" : "goat",
        "Goose" : "goose",
        "Horse" : "horse",
        "Iguana" : "iguana iguana2",
        "Jellyfish" : "jelly_fish",
        "Kangaroo" : "kangaroo",
        "Lion" : "lion lion2",
        "Lamb" : "lamb",
        "Monkey" : "monkey monkey3",
        "Mouse" : "Mouse mouse4",
        "Octopus" : "octopus eight_octopus",
        "Owl" : "owl four_owl",
        "Panda" : "panda panda2",
        "Pig" : "pig pig2",
        "Rabbit" : "rabbit rabbit2",
        "Raccoon" : "raccoon raccoon2",
        "Snake" : "snake",
        "Tiger" : "tiger tiger5",
        "Turtle" : "turtle turtle3",
        "Unicorn" : "unicorn unicorn5",
        "Vulture" : "vulture vulture2",
        "Whale" : "whale whale3",
        "Xenops" : "Xenops",
        "Yak" : "yak yak3",
        "Zebra" : "zebra three_zebra"
]

var imageAnimalDict: [String: [String]] = [
        "Ant" : ["ant", "six_ants"],
        "Bear" : ["bear"],
        "Cat" : ["cat", "three_cats"],
        "Dog" : ["dog"],
        "Duck" : ["duck", "five_duck"],
        "Elephant" : ["elephant", "elephant2", "three_elephant", "four_elephant"],
        "Eagle" : ["eagle"],
        "Frog" : ["frog", "frog2", "frog3"],
        "Goat" : ["goat"],
        "Goose" : ["goose"],
        "Horse" : ["horse"],
        "Iguana" : ["iguana", "iguana2"],
        "Jellyfish" : ["jelly_fish"],
        "Kangaroo" : ["kangaroo"],
        "Lion" : ["lion", "lion2"],
        "Lamb" : ["lamb"],
        "Monkey" : ["monkey", "monkey2", "monkey3"],
        "Mouse" : ["Mouse", "mouse2", "Mouse3", "mouse4"],
        "Octopus" : ["octopus", "octopus2", "eight_octopus"],
        "Owl" : ["owl", "owl2", "owl3", "four_owl"],
        "Panda" : ["panda", "panda2"],
        "Pig" : ["pig", "pig2"],
        "Rabbit" : ["rabbit", "rabbit2"],
        "Raccoon" : ["raccoon", "raccoon2"],
        "Snake" : ["snake"],
        "Tiger" : ["tiger", "tiger2", "tiger3", "tiger4", "tiger5"],
        "Turtle" : ["turtle", "turtle2", "turtle3"],
        "Unicorn" : ["unicorn", "unicorn2", "unicorn3", "unicorn4", "unicorn5"],
        "Vulture" : ["vulture", "vulture2"],
        "Whale" : ["whale", "whale2", "whale3"],
        "Xenops" : ["Xenops"],
        "Yak" : ["yak", "yak2", "yak3"],
        "Zebra" : ["zebra", "zebra2", "three_zebra"]
]